package unam.ciencias.is.kafka.modelo;
// Generated 17/03/2018 02:05:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Responde generated by hbm2java
 */
public class Responde  implements java.io.Serializable {


     private int idResponde;
     private Tema tema;
     private Usuario usuario;
     private String respuesta;
     private Date fecha;

    public Responde() {
    }

    public Responde(int idResponde, Tema tema, Usuario usuario, String respuesta, Date fecha) {
       this.idResponde = idResponde;
       this.tema = tema;
       this.usuario = usuario;
       this.respuesta = respuesta;
       this.fecha = fecha;
    }
   
    public int getIdResponde() {
        return this.idResponde;
    }
    
    public void setIdResponde(int idResponde) {
        this.idResponde = idResponde;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


