package unam.ciencias.is.kafka.modelo;
// Generated 17/03/2018 02:05:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private int idTag;
     private String valor;
     private Set temaTags = new HashSet(0);

    public Tag() {
    }

	
    public Tag(int idTag) {
        this.idTag = idTag;
    }
    public Tag(int idTag, String valor, Set temaTags) {
       this.idTag = idTag;
       this.valor = valor;
       this.temaTags = temaTags;
    }
   
    public int getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(int idTag) {
        this.idTag = idTag;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Set getTemaTags() {
        return this.temaTags;
    }
    
    public void setTemaTags(Set temaTags) {
        this.temaTags = temaTags;
    }




}


