package unam.ciencias.is.kafka.modelo;
// Generated 17/03/2018 02:05:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String correo;
     private String nombre;
     private String contrasena;
     private String imagen;
     private String rol;
     private String estado;
     private Set respondes = new HashSet(0);
     private Set temas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String correo, String nombre, String contrasena, String rol, String estado) {
        this.idUsuario = idUsuario;
        this.correo = correo;
        this.nombre = nombre;
        this.contrasena = contrasena;
        this.rol = rol;
        this.estado = estado;
    }
    public Usuario(int idUsuario, String correo, String nombre, String contrasena, String imagen, String rol, String estado, Set respondes, Set temas) {
       this.idUsuario = idUsuario;
       this.correo = correo;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.imagen = imagen;
       this.rol = rol;
       this.estado = estado;
       this.respondes = respondes;
       this.temas = temas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRespondes() {
        return this.respondes;
    }
    
    public void setRespondes(Set respondes) {
        this.respondes = respondes;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }




}


